# These two notations are equivalent:
# exampleprop: [ref, x, d, ref]
# exampleprop:
#   patterns: ['^exampleprop$']
#   struct: [ref, x, d, ref]
#
# If property name matches pattern, struct is applied for dereferencing phandles
# If no struct is given, consider struct is dynamic:
#  - first element is a ref
#  - if property being parsed is named 'clock', then number of cells is indicated by '#clock-cells' property of referenced object
#  - cells follow ref and are kept as numbers
#  - after cells comes next ref
address:
  patterns: ['interrupt-parent', 'operating-points-v2']
reg: [x, x, d, x]
cpu-idle-states:
  patterns: ['cpu-idle-states']
  struct: [ref, ref]
clock:
  patterns: ['^clocks$', '-clocks$']
io-channel:
  patterns: ['^io-channels$']
power-domain:
  patterns: ['^power-domains$']
pm_qos:
  patterns: ['^pm_qos$']
  struct: [ref]
thermal-sensor:
  patterns: ['^thermal-sensors$']
trip: [ref]
cooling:
  patterns: ['^cooling-device$']
dma:
  patterns: ['^dmas$']
phy:
  patterns: ['^phys$']
reset:
  patterns: ['^resets$']
iommmu:
  patterns: ['^iommus$']
gpio:
  patterns: ['^gpios?$', '-gpios?$', '_gpio$', '_irq$']
pwm:
  patterns: ['^pwms$']
devfreq-events: [ref]
interrupts: [$gic, d, $interrupt-level]
interrupt-affinity: [ref]
remote-endpoint: [ref]
ports: [ref]
supply:
  patterns: ['.*-supply$']
  struct: [ref]
sound-dai: [ref]
pinctrl:
  patterns: ['^pinctrl-']
  struct: [ref, ref, ref, ref, ref]


##############################################################
# CONSTANT DEREFERENCE MAPPINGS
##############################################################

$mapping-gic:
  $include: "<dt-bindings/interrupt-controller/arm-gic.h>"
  0: GIC_SPI
  1: GIC_PPI
  2: GIC_ESPI
  3: GIC_EPPI

$mapping-interrupt-level:
  $include: "<dt-bindings/interrupt-controller/irq.h>"
  0: IRQ_TYPE_NONE
  1: IRQ_TYPE_EDGE_RISING
  2: IRQ_TYPE_EDGE_FALLING
  3: IRQ_TYPE_EDGE_BOTH
  4: IRQ_TYPE_LEVEL_HIGH
  8: IRQ_TYPE_LEVEL_LOW

$mapping-gpio-active:
  $include: "<dt-bindings/gpio/gpio.h>"
  0: GPIO_ACTIVE_HIGH
  1: GPIO_ACTIVE_LOW
